name: nutrition_questionnaire
description:  A Nutrition questionnaire.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^0.4.0+1
  firebase_remote_config: ^0.2.0+7
  firebase_analytics: ^5.0.2
  
  flutter_launcher_icons: ^0.7.3
  dots_indicator: ^1.0.0
  scoped_model: ^1.0.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/graphics/launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/graphics/headers/question_1_header/question_1_header.png
    - assets/graphics/headers/question_1_header/question_1_header.png
    - assets/graphics/headers/question_1_header/question_1_header@2x.png
    - assets/graphics/headers/question_1_header/question_1_header@3x.png
    - assets/graphics/headers/question_2_header/question_2_header.png
    - assets/graphics/headers/question_2_header/question_2_header@2x.png
    - assets/graphics/headers/question_2_header/question_2_header@3x.png
    - assets/graphics/headers/question_3_header/question_3_header.png
    - assets/graphics/headers/question_3_header/question_3_header@2x.png
    - assets/graphics/headers/question_3_header/question_3_header@3x.png
    - assets/graphics/headers/question_4_header/question_4_header.png
    - assets/graphics/headers/question_4_header/question_4_header@2x.png
    - assets/graphics/headers/question_4_header/question_4_header@3x.png
    - assets/graphics/headers/question_5_header/question_5_header.png
    - assets/graphics/headers/question_5_header/question_5_header@2x.png
    - assets/graphics/headers/question_5_header/question_5_header@3x.png
    - assets/graphics/headers/question_6_header/question_6_header.png
    - assets/graphics/headers/question_6_header/question_6_header@2x.png
    - assets/graphics/headers/question_6_header/question_6_header@3x.png
    - assets/graphics/headers/
    - assets/graphics/launcher_icon.png
    - assets/remote_config.json
